from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql as mdb
from PyQt5.QtCore import QFileInfo
from PyQt5.QtWidgets import QFileDialog
from addCateg import addCategDialog
from addManuf import addManufDialog

from err import errDialog


def errfun():
    dialog = errDialog()
    dialog.exec_()


def dbret():
    db = mdb.connect(host='localhost',
                     user='root',
                     password='1234',
                     database='shopdb')
    return db


class addGoodDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super(addGoodDialog, self).__init__(parent)
        self.setObjectName("Dialog")
        self.resize(640, 640)
        self.setMinimumSize(QtCore.QSize(640, 640))
        self.setMaximumSize(QtCore.QSize(640, 640))
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self)
        self.doubleSpinBox_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setMaximum(9999999.99)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_3)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self)
        self.doubleSpinBox_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_4.setFont(font)
        self.doubleSpinBox_4.setMaximum(9999999.99)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_4)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self)
        self.doubleSpinBox_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_5.setFont(font)
        self.doubleSpinBox_5.setMaximum(9999999.99)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_5)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self)
        self.doubleSpinBox_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_6.setFont(font)
        self.doubleSpinBox_6.setMaximum(9999999.99)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_6)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.gridLayout.addLayout(self.horizontalLayout_9, 8, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(self)
        self.pushButton_4.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_11.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self)
        self.pushButton_5.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.gridLayout.addLayout(self.horizontalLayout_11, 14, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self)
        self.pushButton_3.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.gridLayout.addLayout(self.horizontalLayout_10, 9, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setMaximum(9999999.99)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox)
        self.spinBox = QtWidgets.QSpinBox(self)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(9999999)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self)
        self.doubleSpinBox_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setMaximum(5.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_2 = QtWidgets.QComboBox(self)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self)
        self.label_11.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.gridLayout.addLayout(self.horizontalLayout_12, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEdit_3 = QtWidgets.QLineEdit(self)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_13.addWidget(self.lineEdit_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_13.addWidget(self.lineEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout_13, 3, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.gridLayout.addLayout(self.horizontalLayout_14, 12, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_15.addWidget(self.plainTextEdit)
        self.gridLayout.addLayout(self.horizontalLayout_15, 13, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.gridLayout.addLayout(self.horizontalLayout_16, 10, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lineEdit_4 = QtWidgets.QLineEdit(self)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_17.addWidget(self.lineEdit_4)
        self.gridLayout.addLayout(self.horizontalLayout_17, 11, 0, 1, 1)
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Добавление товара"))
        self.label_10.setText(_translate("Dialog", "Изображение"))
        self.label_6.setText(_translate("Dialog", "Вес"))
        self.label_7.setText(_translate("Dialog", "Ширина"))
        self.label_8.setText(_translate("Dialog", "Высота"))
        self.label_9.setText(_translate("Dialog", "Толщина"))
        self.pushButton_4.setText(_translate("Dialog", "Добавить"))
        self.pushButton_5.setText(_translate("Dialog", "Отмена"))
        self.pushButton_3.setText(_translate("Dialog", "Обзор"))
        self.label_3.setText(_translate("Dialog", "Цена"))
        self.label_4.setText(_translate("Dialog", "Количество"))
        self.label_5.setText(_translate("Dialog", "Оценка"))
        self.pushButton.setText(_translate("Dialog", "+"))
        self.pushButton_2.setText(_translate("Dialog", "+"))
        self.label_12.setText(_translate("Dialog", "Артикул"))
        self.label_11.setText(_translate("Dialog", "Модель"))
        self.label.setText(_translate("Dialog", "Категория"))
        self.label_2.setText(_translate("Dialog", "Производитель"))
        self.label_13.setText(_translate("Dialog", "Описание товара"))
        self.label_14.setText(_translate("Dialog", "Короткое описание характеристик"))
        self.pushButton_4.clicked.connect(self.addLogic)
        self.pushButton_5.clicked.connect(self.close)
        self.pushButton_3.clicked.connect(self.openPicture)
        self.pushButton.clicked.connect(self.addCategory)
        self.pushButton_2.clicked.connect(self.addManufacturer)
        self.addComboBoxData()

    def addComboBoxData(self):
        self.comboBox.clear()
        self.comboBox_2.clear()
        db = dbret()
        cur = db.cursor()
        cur.execute('select name from categories')
        data = cur.fetchall()
        self.comboBox.addItem("Категории")
        for i in range(len(data)):
            self.comboBox.addItem(str(data[i][0]))
        cur.execute("select name from manufacturers")
        data = cur.fetchall()
        self.comboBox_2.addItem("Производители")
        for i in range(len(data)):
            self.comboBox_2.addItem(str(data[i][0]))
        db.close()

    def openPicture(self):
        file, _ = QFileDialog.getOpenFileName(None, 'Open File', 'D:\Other\Diplom\WebPCShop\static\images', "Image (*.png *.jpg *jpeg)")
        self.lineEdit.setText(QFileInfo(file).fileName())

    def addCategory(self):
        add = addCategDialog()
        add.exec_()
        self.addComboBoxData()

    def addManufacturer(self):
        add = addManufDialog()
        add.exec_()
        self.addComboBoxData()

    def addLogic(self):
        category = self.comboBox.currentIndex()
        manufacturer = self.comboBox_2.currentIndex()
        articul = self.lineEdit_3.text()
        model = self.lineEdit_2.text()
        price = self.doubleSpinBox.value()
        count = self.spinBox.value()
        opinion = self.doubleSpinBox_2.value()
        weight = self.doubleSpinBox_3.value()
        x = self.doubleSpinBox_4.value()
        y = self.doubleSpinBox_5.value()
        z = self.doubleSpinBox_6.value()
        picture = self.lineEdit.text()
        disc = self.plainTextEdit.toPlainText()
        shortDisc = self.lineEdit_4.text()
        check = True
        try:
            int(articul)
        except ValueError:
            errfun()
            check = False
        if category == 0 or manufacturer == 0 or model == "" or count == 0 or price == 0 or opinion == 0:
            errfun()
            check = False
        if check:
            db = dbret()
            cur = db.cursor()
            sql = (
                'insert into goods (articul, model, price, picture, count, opinion, weight, x, y, z, disc, shortDisc, categories_idcategories, '
                'manufacturers_idmanufacturers) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)')
            val = (articul, model, price, picture, count, opinion, weight, x, y, z, disc, shortDisc, category, manufacturer)
            cur.execute(sql, val)
            db.commit()
            db.close()
            self.close()
